#!/usr/bin/env zsh
xset s blank
xset s 600
xset dpms 1200 1800 2400
xsetroot -solid black
setxkbmap us dvorak
[ -f ~/.zshrc ] && . ~/.zshrc
[ -f ~/.xprofile ] && . ~/.xprofile
[ -e ~/.Xmodmap ] && xmodmap ~/.Xmodmap
xscreensaver -nosplash &
# autocutsel -f -s CLIPBOARD
# autocutsel -f -s PRIMARY
redshift-palo-alto &
# /usr/bin/xscreensaver -nosplash &
# ~/bin/redshift-mountain-view &
