#!/usr/bin/env bash

# Logging setup
LOGFILE="/tmp/xinitrc.log"
echo "$(date): Starting xinitrc" > "$LOGFILE"

# X11 setup
xset s blank
xset s 600
xset dpms 1200 1800 2400
xsetroot -solid black
[ -f ~/.zshrc ] && . ~/.zshrc
[ -f ~/.xprofile ] && . ~/.xprofile
[ -e ~/.Xmodmap ] && xmodmap ~/.Xmodmap

# Background services
echo "$(date): Starting background services" >> "$LOGFILE"
xscreensaver -nosplash &
sxhkd &
tmux new -A -s work &
redshift-palo-alto &

# Display setup
echo "$(date): Setting up display" >> "$LOGFILE"
xrandr --dpi 96
autorandr --change --default standalone

# Log keyboard state before EXWM
echo "$(date): Keyboard state before EXWM:" >> "$LOGFILE"
setxkbmap -query >> "$LOGFILE" 2>&1

# Set keyboard options for internal keyboard specifically
setxkbmap -device 13 -option caps:ctrl_modifier,compose:menu

# Start i3
echo "$(date): Starting i3" >> "$LOGFILE"
exec i3 2>&1 | tee -a "$LOGFILE"
