#+PROPERTY: header-args :shebang #!/usr/bin/env sh
* Installing redshift with randr
  Requires =sudo apt-get install libxcb-randr0*= first.
* Solving “could not find function .ess.eval”
  For some reason, =ess-etc-directory= seems to be misconfigured after
  elpa-refresh; had to do e.g. =(setq ess-etc-directory
  "~/.emacs.d/elpa/ess-20180808.852/etc")= manually.

  Maybe =M-x load-library RET ess-site RET= would have sufficed?
* Setting default keyoard-layout in console
  In Debian-likes, modify [[file:/etc/default/keyboard][/etc/default/keyboard]], setting:

  #+BEGIN_SRC sh
    XKBVARIANT="dvorak"
    XKBOPTIONS="terminate:ctrl_alt_bksp"

  and then see [[https://askubuntu.com/a/930440][this]]: =sudo update-initramfs -u=.
  #+END_SRC
* Booting to runlevel 3
  In Debian-likes, modify [[file:/etc/default/grub][/etc/default/grub]], setting:
  
  #+BEGIN_SRC sh
    GRUB_CMDLINE_LINUX_DEFAULT="text"
  #+END_SRC
  
  Also issue this to prevent it from being modified on update:

  #+BEGIN_SRC sh
    sudo chattr +i /etc/default/grub
  #+END_SRC
* “X: user not authorized to run the X server, aborting.”
  Edit [[file:/etc/X11/Xwrapper.config][/etc/X11/Xwrapper.config]], setting
  =allowed_users= to =anybody=; or run =dpkg-reconfigure x11-common= in
  Debian-likes.
* Building stumpwm
  To install surfraw, etc.; do:

  #+BEGIN_SRC sh :tangle stumpwm-install-modules
    make install-modules
  #+END_SRC
* Building bitlbee
  See e.g. [[https://wiki.bitlbee.org/HowtoGtalk][Gtalk]]:
  
  #+BEGIN_EXAMPLE
    acc add jabber ...@gmail.com
    acc jabber set nick_format %full_name
    acc jabber set oauth on
    acc jabber set server talk.google.com
    acc jabber on
  #+END_EXAMPLE

  Incidentally, see [[https://bitbucket.org/EionRobb/purple-hangouts][purple-hangouts]] for non-XMPP Hangouts support (including
  group chats and SMS via Voice); also [[https://github.com/tdryer/hangups][hangups]], which is the basis for
  [[https://github.com/ZeWaren/jabber-hangouts-transport][jabber-hangouts-transport]].

  There is [[https://bitbucket.org/EionRobb/purple-hangouts/wiki/Bitlbee_FAQ][some mention]] of bitlbee in the purple-hangouts wiki; also, [[https://github.com/jaredbranum/voicegate][this
  Voice-to-XMPP]] never got working.

  Someone got [[https://demu.red/blog/2016/12/setting-up-sms-in-irc-via-bitlbee-with-purple-hangouts/][bitlbee working with purple-hangouts]], but this depends on the
  deprecated support for SMS within hangouts.

  There’s this [[https://github.com/bentglasstube/bitlbee-gvoice][Voice-plugin]] for bitlbee; how does it work?

  [[https://www.reddit.com/r/commandline/comments/mjd1l/has_anyone_figured_out_how_to_google_voice_sms/][This post]] mentions [[https://code.google.com/archive/p/pygooglevoice/][pygooglevoice]], which is defunct, and a “google voice to
  gtalk trick;” not sure what that is, though.

  Actually, [[https://support.google.com/voice/answer/6023920?co=GENIE.Platform%253DDesktop&hl=en][this help page]] doesn’t say anything about Google Voice SMS in
  Hangouts being deprecated; it does say this, though:

  #+BEGIN_QUOTE
  Important: Soon, text messaging (SMS) will only be available in Hangouts if
  you have a Google Voice or Project Fi number.
  #+END_QUOTE

  and [[https://support.google.com/hangouts/answer/3441321][this page]] clarifies:

  #+BEGIN_QUOTE
  Soon, text messaging (SMS & MMS) with your cell phone service’s number will no
  longer work on Hangouts.

  If you use Hangouts as your text messaging app (SMS & MMS), you will need to
  switch to another text messaging app to continue sending and receiving text
  messages (SMS & MMS).  You will get a reminder to switch to another text
  messaging app before the Hangouts text messaging feature goes away.

  You’ll still be able to text on Hangouts through Google Voice and Project Fi.
  #+END_QUOTE
  
  So, looks like we still have to build something propr . . . on the other hand,
  this [[https://github.com/pettazz/pygooglevoice][pygooglevoice]] seems to be under development and claims to have fixed the
  problem.

  These guys seem to have developed an [[https://github.com/twbarber/irc-sms-bot/tree/master/pygooglevoice][IRC-SMS bot]].

  [[http://blog.jwcxz.com/?p=883][JWC thought about building something for Voice and bitlbee]]; claims [[https://weechat.org/][WeeChat]] is
  superior to irssi, by the way!
* Building xscreensaver
  For getting all the hacks, try e.g.:
  
  #+BEGIN_SRC sh :tangle xscreensaver-configure
    ./configure \
        --with-gl \
        --with-gle \
        --with-gles \
        --with-pixbuf \
        --with-jpeg \
        --with-xft \
        --with-xdbe-ext \
        --with-xshm-ext \
        --with-setuid-hacks \
        --with-record-animation
  #+END_SRC

  and in Ubuntu, getting the necessary packages:

  #+BEGIN_SRC sh :tangle xscreensaver-apt-get
    sudo apt-get install \
        intltool \
        libgdk-pixbuf2.0-0 \
        libgdk-pixbuf2.0-dev \
        libxshmfence-dev \
        libgtk2.0-0 \
        libgtk2.0-dev \
        libxml2 libxml2-dev \
        libglade2-0 \
        libglade2-dev \
        libjpeg-dev \
        freeglut3 \
        freeglut3-dev \
        libgle3 \
        libgle3-dev \
        libxmu-dev \
        fortunes \
        fortune-mod \
        fortunes-mario \
        fortunes-off \
        fortunes-spam
  #+END_SRC
* Building emacs
  #+BEGIN_SRC sh :tangle emacs-configure
    ./configure --without-x
  #+END_SRC
** Protobuf errors
   Seeing errors such as:

   #+BEGIN_EXAMPLE
     Error during redisplay: (jit-lock-function 1) signaled (wrong-type-argument stringp nil)
   #+END_EXAMPLE
   
   Cf. e.g. [[https://github.com/google/protobuf/issues/2787][this issue]], in which someone enabled =(toggle-debug-on-error)=;
   apparently, recompiling the package helped.

   This didn’t help us, though! Let’s try recompiling emacs itself.
* Changing the console keybord-layout
  In [[http://askubuntu.com/a/158895][Ubuntu]], try:

  #+BEGIN_SRC sh :tangle console-keyboard
    sudo dpkg-reconfigure keyboard-configuration
  #+END_SRC
* Building privoxy
  #+BEGIN_SRC sh :tangle privoxy-configure
    sudo /usr/sbin/useradd privoxy
    autoheader
    autoconf
    ./configure --with-user=privoxy --with-group=privoxy
  #+END_SRC
* Building R
  Pull the sources down from svn:
  
  #+BEGIN_SRC sh :tangle R-checkout
    svn co https://svn.r-project.org/R/trunk R
  #+END_SRC
  
  Download the recommended packages and build:
  
  #+BEGIN_SRC sh :tangle R-configure
    sh tools/rsync-recommended
    ./configure --enable-R-shlib
  #+END_SRC

  After upgrading, [[http://stackoverflow.com/a/3974549][update all the packages]]:

  #+BEGIN_SRC R :tangle R-update.R :shebang #!/usr/bin/env R
    update.packages(checkBuilt=TRUE, ask=FALSE)
  #+END_SRC
* Building Screen
  #+BEGIN_SRC sh :tangle screen-configure
    ./configure --prefix=/usr/local --enable-colors256
  #+END_SRC

  #+BEGIN_SRC sh :tangle screen-make
    make && sudo make install
    sudo cp -v ./etc/etcscreenrc /usr/local/etc/screenrc
    cd terminfo
    sudo tee -a /etc/termcap < screencap
    sudo tic screeninfo.src
  #+END_SRC
* Creating Gmail filters
  This is how you might create Gmail filters for a set of domains
  where e.g. everything To, Cc or Bcc you goes into the inbox; and
  everything else goes into a Groups label.
  
  #+BEGIN_SRC sh :tangle gmail-filters
    DOMAINS=domains.txt
    domains=$({
                 while read domain; do
                     echo -n "${domain} "
                 done
             } < "${DOMAINS}")

    echo "-{to:{${domains}} cc:{${domains}} bcc:{${domains}} from:{${domains}} label:saved}"
  #+END_SRC

  #+BEGIN_SRC text :tangle domains.txt :shebang
    danenberg.name
    googlerugby.com
    mitdasein.com
    pcd.la
    post.harvard.edu
    roxygen.org
    wikitex.org
  #+END_SRC
* Ad-hoc HTTP-server
  See the [[https://gist.github.com/willurd/5720255][big list]]; this one’s pretty good:

  #+BEGIN_SRC sh :tangle httpd-ad-hoc
    python -m SimpleHTTPServer 8000
  #+END_SRC
* Unpack a gif with partial updates
  See e.g. [[http://www.imagemagick.org/discourse-server/viewtopic.php?t%3D11578][this]]:

  #+BEGIN_SRC sh
    convert google-new.gif -coalesce /tmp/google-new/%03d.gif
  #+END_SRC
* Converting wmv to mp3 for BBC Shakespeare
  #+BEGIN_SRC sh :tangle bbc-shakespeare
    find . -name '*.wmv' -print0 | \
        while read -r -d $'\0' file; do
          mplayer -noconsolecontrols \
                  -ao pcm:fast:file=/tmp/shakespeare.wav \
                  -benchmark \
                  -vc null \
                  -vo null \
                  "${file}" && \
              lame -h /tmp/shakespeare.wav \
                   "${HOME}/doc/snd/shakespeare/${$(basename ${file})%.wmv}.mp3";
        done
  #+END_SRC
* Dictd
  OED, etc.:

  #+BEGIN_SRC sh
    dictd -c etc/dictd.conf --debug nodetach
  #+END_SRC
* Converting MIDI to wav
  Try e.g.

  #+BEGIN_SRC sh
    timidity <midi-file>
  #+END_SRC

  or:

  #+BEGIN_SRC sh
    fluidsynth -F <wav-file> -a alsa -m alsa_seq \
      /usr/share/sounds/sf2/FluidR3_GM.sf2 <midi-file>
  #+END_SRC
* Repairing truncated mp4s
  Try https://github.com/ponchio/untrunc; had to build libav locally.
* Audio
  Mount Android:

  #+BEGIN_SRC sh
    sudo jmtpfs -o allow_other ~/mnt/usb
  #+END_SRC


  Make a video with one frame:

  #+BEGIN_SRC sh
    ffmpeg -loop 1 \
           -i quartet-small.jpg \
           -i fuga-a-die-iræ-quartet-live.wav \
           -shortest \
           fuga-a-die-iræ-quartet-live.mp4
  #+END_SRC
