#!/bin/sh
# elvis: codesearch -- Search source.corp.google.com
. surfraw || exit 1

w3_usage_hook () {
    cat <<EOF
Usage: $w3_argv0 [options] [search terms]...
Description:
  Search code

  Examples:
    $w3_argv0 blame:me
EOF
    w3_global_usage
}

w3_config
w3_parse_args "$@"

if test -z "$w3_args"; then
    w3_browse_url "https://source.corp.google.com"
else
    escaped_args=$(w3_url_of_arg $w3_args)
    w3_browse_url "https://source.corp.google.com/search?q=${escaped_args}"
fi
