#!/bin/sh
# elvis: moma -- Search Moma (https://moma.corp.google.com)
. surfraw || exit 1

w3_usage_hook () {
    cat <<EOF
Usage: $w3_argv0 [options] [search terms]...
Description:
  Search Moma

  Example:
    $w3_argv0 test
EOF
    w3_global_usage
}

w3_config
w3_parse_args "$@"

if test -z "$w3_args"; then
    w3_browse_url "https://moma.corp.google.com"
else
    escaped_args=$(w3_url_of_arg $w3_args)
    w3_browse_url "https://moma.corp.google.com/search?q=${escaped_args}"
fi
