;; This file is automatically generated by the multiple-cursors
;; extension.
;; It keeps track of your preferences for running commands with
;; multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        helm-M-x
        helm-show-kill-ring
        kill-region
        kill-sexp
        mark-sexp
        paredit-forward-delete
        paredit-kill
        paredit-open-round
        paredit-raise-sexp
        smart-open-line
        smarter-move-beginning-of-line
        ))

(setq mc/cmds-to-run-once
      '(
        compile
        reindent-then-newline-and-indent
        ))
