#!/bin/sh
# $Id$
# elvis: gmail	-- Search Gmail (mail.google.com)
. surfraw || exit 1

w3_usage_hook () {
    cat <<EOF
Usage: $w3_argv0 [options] [search words]...
Description:
  Surfraw search Gmail (mail.google.com)
EOF
    w3_global_usage
}

w3_config
w3_parse_args "$@"
# w3_args now contains a list of arguments
if test -z "$w3_args"; then
    w3_browse_url "https://mail.google.com/"
else
    escaped_args=`w3_url_of_arg $w3_args`
    w3_browse_url "https://mail.google.com/mail/u/0/#search/${escaped_args}"
fi
