#!/bin/sh
# $Id$
# elvis: oed	-- Search OED (www.oed.com)
. surfraw || exit 1

w3_usage_hook () {
    cat <<EOF
Usage: $w3_argv0 [options] [search words]...
Description:
  Surfraw search OED (www.oed.com)
EOF
    w3_global_usage
}

w3_config
w3_parse_args "$@"
# w3_args now contains a list of arguments
if test -z "$w3_args"; then
    w3_browse_url "http://www.oed.com/"
else
    escaped_args=`w3_url_of_arg $w3_args`
    w3_browse_url "http://oed.com/search?searchType=dictionary&q=${escaped_args}"
fi
